var files_dup =
[
    [ "Bitmap.cpp", "_bitmap_8cpp.html", null ],
    [ "Bitmap.h", "_bitmap_8h.html", "_bitmap_8h" ],
    [ "DetailsPanel.cpp", "_details_panel_8cpp.html", null ],
    [ "DetailsPanel.h", "_details_panel_8h.html", "_details_panel_8h" ],
    [ "Enemy.cpp", "_enemy_8cpp.html", null ],
    [ "Enemy.h", "_enemy_8h.html", "_enemy_8h" ],
    [ "FlameGraph.cpp", "_flame_graph_8cpp.html", null ],
    [ "FlameGraph.h", "_flame_graph_8h.html", "_flame_graph_8h" ],
    [ "Game.cpp", "_game_8cpp.html", "_game_8cpp" ],
    [ "Game.h", "_game_8h.html", "_game_8h" ],
    [ "Hero.cpp", "_hero_8cpp.html", null ],
    [ "Hero.h", "_hero_8h.html", "_hero_8h" ],
    [ "I_GUIWindow.h", "_i___g_u_i_window_8h.html", "_i___g_u_i_window_8h" ],
    [ "Input.cpp", "_input_8cpp.html", null ],
    [ "Input.h", "_input_8h.html", "_input_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "MeatPickup.cpp", "_meat_pickup_8cpp.html", null ],
    [ "MeatPickup.h", "_meat_pickup_8h.html", "_meat_pickup_8h" ],
    [ "Profiler.cpp", "_profiler_8cpp.html", "_profiler_8cpp" ],
    [ "Profiler.h", "_profiler_8h.html", "_profiler_8h" ],
    [ "TextureManager.cpp", "_texture_manager_8cpp.html", null ],
    [ "TextureManager.h", "_texture_manager_8h.html", "_texture_manager_8h" ]
];